language: node_js

node_js:
  - '0.10'

before_script:
  - npm install -g codeclimate-test-reporter

after_script:
  - codeclimate < test/coverage/**/lcov.info

notifications:
  # publish build status to IRC channel: #graspjs
  irc:
    channels:
    - chat.freenode.net#graspjs
    on_success: always
    on_failure: always
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
  # publish build status to gitter chat room: https://gitter.im/daniellmb/graspjs
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/a9604c7a34ea083535bd
    on_success: always
    on_failure: always
    on_start: false

env:
  - CODECLIMATE_REPO_TOKEN=b1b5a6ca2dc110214ff3609a1d775695f583ef05419dcf451e8ec0c379b9017b